const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const content = fs.readFileSync(path.join(root, "content.js"), "utf8");
const options = fs.readFileSync(path.join(root, "options.html"), "utf8");
const popup = fs.readFileSync(path.join(root, "popup.html"), "utf8");
const optionsJs = fs.readFileSync(path.join(root, "options.js"), "utf8");
const background = fs.readFileSync(path.join(root, "background.js"), "utf8");
const apiJs = fs.readFileSync(path.join(root, "doctolib-api.js"), "utf8");
const coreJs = fs.readFileSync(path.join(root, "quick-search-core.js"), "utf8");
const endpointScript = fs.readFileSync(path.join(root, "scripts", "test-endpoints.js"), "utf8");

assert(manifest.version === "1.0.89", "manifest version should be 1.0.89");
assert(manifest.permissions.includes("contextMenus"), "context menu permission should be declared");
assert(manifest.permissions.includes("scripting"), "popup should be able to execute autocomplete in the Doctolib page context");
assert(manifest.permissions.includes("tabs"), "popup should be able to query the Doctolib tab for native autocomplete");
assert(!content.includes("Trajet estimé · marge"), "useless margin fallback should be removed");
assert(manifest.action.default_popup === "popup.html", "popup should be popup.html");
assert(manifest.options_ui.page === "options.html", "options page should remain options.html");
assert(content.includes("calendar.google.com/calendar/render"), "calendar link should exist");
assert(content.includes("doctorAutocomplete"), "content script should proxy Doctolib autocomplete from page context");
assert(content.includes("Copier l'adresse"), "copy action should exist");
assert(content.includes("Voir l'entrée"), "entrance action should exist");
assert(content.includes("Heure du RDV non détectée"), "missing appointment fallback should exist");
assert(content.includes("Actuelle"), "current weather label should exist");
assert(content.includes("RDV"), "appointment weather label should exist");
assert(content.includes("normalizeSettings"), "settings should be normalized");
assert(content.includes("return { ...DEFAULT_SETTINGS };"), "content script should fall back when extension context is invalidated");
assert(content.includes("streetViewUrl"), "street view action should exist");
assert(content.includes("Europe/Paris"), "calendar should force France timezone");
assert(content.includes("calendarDateParis"), "calendar should use Paris local dates");
assert(content.includes("Calendrier indispo"), "calendar should be disabled without appointment date");
assert(content.includes("loadAppointmentDetails"), "appointment detail data should be loaded from API");
assert(content.includes("fetch(`/appointments/${encodeURIComponent(id)}`"), "appointment details should use Doctolib JSON endpoint");
assert(content.includes("details?.practice?.full_address"), "destination should come from API practice details");
assert(content.includes("appointment?.start_date"), "appointment date should come from API details");
assert(!content.includes("findAddressNear"), "destination should not be parsed from DOM text");
assert(!content.includes("appointmentDateTimeNear"), "appointment date should not be parsed from DOM text");
assert(!content.includes("parseFrenchDateTime"), "appointment date parser should not be needed for API-backed details");
assert(content.includes("main-card-appointment-details"), "main appointment card should be targeted");
assert(content.includes("FACILITY_DETAILS_TEXT"), "facility details card should be targeted");
assert(content.includes("moveFacilityDetailsCard"), "facility card moving should exist");
assert(content.includes("document.querySelector(\".main-card-appointment-details\")"), "facility move should search appointment card globally");
assert(!content.includes("h1, h2, h3, h4, p, span, div"), "facility search should not scan broad text nodes");
assert(content.includes("storeUpcomingAppointments"), "upcoming appointments should be stored");
assert(content.includes("root?.querySelectorAll ? root : document"), "scan should ignore non-element mutation roots");
assert(content.includes("chrome.storage?.local"), "upcoming appointments should use local storage");
assert(popup.includes("appointments-list"), "popup should render upcoming appointments");
assert(popup.includes("cancel-dialog"), "popup should include a cancel confirmation dialog");
assert(popup.includes("quick-search-form"), "popup should include quick Doctolib search");
assert(popup.includes("quick-search-submit"), "popup should have an explicit quick search button");
assert(popup.includes("quick-search-doctor"), "quick search should accept a doctor name");
assert(popup.includes("doctor-suggestions"), "quick search should render selectable doctor matches");
assert(popup.includes("Toutes spécialités"), "quick search should default to no specialty filter");
assert(popup.includes("chirurgien-oral"), "quick search should include oral surgery");
assert(popup.includes("urologue"), "quick search should include a broader specialty catalog");
assert(popup.includes("quick-search-core.js"), "popup should load shared quick search helpers");
assert(popup.includes("doctolib-api.js"), "popup should load shared Doctolib API client");
assert(popup.includes("paris-75007"), "quick search should include Paris arrondissement choices");
assert(popup.includes("recent-searches"), "popup should show recent quick searches");
assert(!popup.includes("departure-alert"), "popup should not include vague departure alerts");
assert(popup.includes("data-search-specialty"), "popup should include favorite search shortcuts");
assert(
  popup.indexOf("Dentiste") < popup.indexOf("Dermato") &&
  popup.indexOf("Dermato") < popup.indexOf("Généraliste") &&
  popup.indexOf("Généraliste") < popup.indexOf("Gynéco") &&
  popup.indexOf("Gynéco") < popup.indexOf("Kinésithérapeute") &&
  popup.indexOf("Kinésithérapeute") < popup.indexOf("Ophtalmo") &&
  popup.indexOf("Ophtalmo") < popup.indexOf("ORL") &&
  popup.indexOf("ORL") < popup.indexOf("Orthoptiste") &&
  popup.indexOf("Orthoptiste") < popup.indexOf("Radiologue"),
  "quick search specialties should be sorted by label"
);
assert(!popup.includes("chirurgien-dentiste"), "quick search default should not use Doctolib-invalid dentist slug");
assert(!popup.includes("settings-form"), "popup should not show settings");
assert(popup.includes("open-options"), "popup should link to extension options");
assert(optionsJs.includes("chrome.runtime.openOptionsPage"), "popup options link should use Chrome options API");
assert(optionsJs.includes("quickSearchUrl"), "quick search should build Doctolib URLs");
assert(optionsJs.includes("https://www.doctolib.fr/${specialty}/${location}"), "quick search should open Doctolib result pages");
assert(optionsJs.includes("https://www.doctolib.fr/search"), "doctor name search should use Doctolib search URL");
assert(optionsJs.includes("searchLocationParam"), "doctor name search should build location query params");
assert(optionsJs.includes("postalCode ? `${postalCode}-paris`"), "doctor name search should use Doctolib location slug format");
assert(optionsJs.includes("normalizeDoctorSearch"), "doctor name search should clean title prefixes");
assert(optionsJs.includes("selectedSearchSegment"), "quick search should fall back to enabled default selections");
assert(optionsJs.indexOf("chrome.tabs.create({ url }") < optionsJs.indexOf("rememberQuickSearch(safeSpecialty"), "quick search should open tabs before storing history");
assert(optionsJs.includes("quickSearchSubmit"), "quick search button should have an explicit click handler");
assert(optionsJs.includes("rememberQuickSearch"), "quick search should store recent searches");
assert(optionsJs.includes("quickSearchRecent"), "recent searches should use a local storage key");
assert(optionsJs.includes("FAVORITE_SEARCHES"), "recent searches should hide favorite duplicates");
assert(!optionsJs.includes("renderDepartureAlert"), "popup should not render vague departure alerts");
assert(optionsJs.includes("appointmentDisplayLimit"), "popup should support compact display limits");
assert(optionsJs.includes("appointmentDensity"), "popup should normalize display density");
assert(optionsJs.includes("updateAppointmentBadge"), "popup should request badge updates");
assert(optionsJs.includes("SuperDoctolibApi"), "popup should use the shared Doctolib API client");
assert(optionsJs.includes("SuperDoctolibCore"), "popup should use shared pure helper functions");
assert(optionsJs.includes("AVAILABILITY_CACHE_TTL_MS"), "availability cache should have a TTL");
assert(optionsJs.includes("syncQuickSearchSpecialties"), "quick search specialties should adapt to the selected patient");
assert(optionsJs.includes("isLikelyMalePatient"), "quick search should detect likely male patient names defensively");
assert(optionsJs.includes("gynecologue-medical-et-obstetrique"), "quick search should be able to hide gynecology for male patients");
assert(background.includes("chrome.action.setBadgeText"), "background should update the action badge");
assert(background.includes("upcomingAppointmentCount"), "background badge should count upcoming appointments defensively");
assert(background.includes("contextMenus"), "background should register a context menu");
assert(background.includes("Rechercher ce médecin sur Doctolib"), "context menu should search selected doctor names");
assert(background.includes("normalizeDoctorSelection"), "context menu should clean selected doctor names");
assert(background.includes("void chrome.runtime.lastError"), "context menu lifecycle should consume expected Chrome runtime errors");
assert(endpointScript.includes("GET /availabilities.json"), "endpoint test script should be read-only");
assert(endpointScript.includes("READ_ONLY_COMMANDS"), "endpoint test script should reject destructive commands");
assert(!endpointScript.includes("method: \"DELETE\""), "endpoint test script must not delete appointments");
assert(!endpointScript.includes("/move/new"), "endpoint test script must not move appointments");
assert(options.includes("settings-form"), "options should show settings");
assert(options.includes("quick-search-core.js"), "options should load shared quick search helpers");
assert(options.includes("doctolib-api.js"), "options should load shared Doctolib API client");
assert(apiJs.includes("cancelAppointment"), "Doctolib API client should centralize cancellation");
assert(apiJs.includes("availabilities"), "Doctolib API client should centralize availability checks");
assert(apiJs.includes("/api/searchbar/autocomplete.json"), "doctor name validation should use Doctolib searchbar autocomplete");
assert(apiJs.includes("url.searchParams.set(\"search\", search)"), "doctor name validation should use the real searchbar query param");
assert(apiJs.includes("doctorSearchQueries"), "doctor search should try multiple Doctolib autocomplete query forms");
assert(apiJs.includes("`dr ${withoutTitle}`"), "doctor search should include Doctolib's lowercase dr query");
assert(apiJs.includes("for (const search of searches)"), "doctor search should run all query attempts inside the Doctolib page context");
assert(apiJs.includes("meta[name='csrf-token']"), "doctor autocomplete should send Doctolib's page CSRF token");
assert(apiJs.includes("\"x-csrf-token\""), "doctor autocomplete should match Doctolib autocomplete headers");
assert(apiJs.includes("DOCTOR_SEARCH_CACHE_TTL_MS"), "doctor autocomplete should use a short-lived cache");
assert(apiJs.includes("createTtlCache"), "doctor autocomplete cache should use a reusable TTL cache abstraction");
assert(apiJs.includes("while (store.size > limit)"), "doctor autocomplete cache should be bounded");
assert(apiJs.includes("searchbarAutocompleteFromDoctolibTab"), "doctor autocomplete should prefer the active Doctolib page context");
assert(apiJs.includes("chrome.scripting.executeScript"), "doctor autocomplete should run in Doctolib's main page world");
assert(apiJs.includes("world: \"MAIN\""), "doctor autocomplete should use the page main world for Doctolib fetch");
assert(apiJs.includes("preferredDoctolibTab"), "doctor autocomplete should pick the best Doctolib tab deterministically");
assert(apiJs.includes("createTemporaryDoctolibTab"), "doctor autocomplete should create a temporary Doctolib page when no tab is open");
assert(apiJs.includes("closeTemporaryTab"), "temporary Doctolib autocomplete tab should be closed");
assert(apiJs.includes("tabs?.remove?.(tabId)).catch"), "temporary tabs should be closed without unhandled promise leaks");
assert(!apiJs.includes("return searchbarAutocomplete(keyword, signal);"), "doctor autocomplete must not silently fall back to extension fetch");
assert(!apiJs.includes("shouldKeepAutocompleteResult"), "single-token doctor search should not keep non-profile autocomplete results");
assert(optionsJs.includes("normalizeDoctorSuggestions"), "doctor name validation should normalize autocomplete suggestions");
assert(optionsJs.includes("setDoctorStatus"), "doctor search UI states should be centralized");
assert(optionsJs.includes("payload?.profiles"), "doctor name validation should read profile suggestions from autocomplete");
assert(optionsJs.includes("isAmbiguous"), "doctor name validation should avoid false exact matches when several profiles match");
assert(optionsJs.includes("showDoctorSuggestions"), "ambiguous doctor searches should show selectable matches");
assert(optionsJs.includes("selectDoctorProfile"), "doctor suggestion selection should only select the profile");
assert(optionsJs.includes("suppressDoctorValidation"), "doctor suggestion selection should not trigger another validation search");
assert(optionsJs.includes("selectingDoctorSuggestion"), "doctor suggestion selection should suppress blur-triggered validation");
assert(optionsJs.includes("\"pointerdown\""), "doctor suggestion selection should happen before input blur");
assert(optionsJs.includes("doctorSuggestionByUrl"), "doctor suggestions should use delegated events instead of per-item listeners");
assert(optionsJs.includes("formatProviderName"), "selected doctor profile should format the search input label");
assert(optionsJs.includes("clique la loupe"), "selected doctor profile should wait for the explicit search button");
assert(optionsJs.includes("sélectionne un profil"), "doctor profiles should require explicit selection before opening");
assert(optionsJs.includes("match.matches.length > 0"), "single doctor profile should also be shown as a selectable suggestion");
assert(optionsJs.includes("event.stopPropagation()"), "doctor suggestion clicks should not bubble to the search form");
assert(optionsJs.includes("Choisis un profil dans la liste"), "doctor search submit should wait for an explicit profile choice");
assert(optionsJs.includes("doctorSuggestionMatches"), "doctor search should keep suggestion state for explicit selection");
assert(optionsJs.includes("doctorSearchErrorMessage"), "doctor search should surface technical errors instead of false empty states");
assert(optionsJs.includes("Aucun profil reçu"), "doctor search empty state should mention profile payloads");
assert(optionsJs.includes("matchedQuery"), "doctor search empty state should show the query that returned no profiles");
assert(optionsJs.includes("firstNonEmptySample"), "doctor search diagnostics should surface response samples");
assert(optionsJs.includes("SPECIALTY_ALIASES"), "doctor suggestions should support specialty filtering");
assert(optionsJs.includes("filterDoctorSuggestionsBySpecialty"), "doctor suggestions should filter by selected specialty");
assert(optionsJs.includes("filterDoctorSuggestionsByLocation"), "doctor suggestions should filter by selected location when available");
assert(optionsJs.includes("selectedSpecialtySegment"), "empty specialty should remain an explicit no-filter state");
assert(coreJs.includes("selectedSearchSegment"), "quick search core should expose tested selection helpers");
assert(options.includes("appointment-density"), "options should include compact/comfortable display setting");
assert(!options.includes("appointments-list"), "options should not show the appointment list");
assert(!options.includes("settings-header"), "options should not duplicate the Chrome options header");
assert(content.includes("/account/appointments.json?page=0"), "appointments should come from Doctolib JSON API");
assert(content.includes("is_in_future === true"), "past appointments should be filtered out");
assert(content.includes("normalizeAppointmentsPayload"), "appointments JSON payload should be normalized");
assert(!content.includes("upcomingAppointmentCardsFromList"), "upcoming list should not be scraped from the DOM");
assert(!content.includes("extractAppointmentSummary"), "upcoming appointments should not be reconstructed from DOM cards");
assert(content.includes("account/appointments/details"), "stored appointment links should use the account detail route");
assert(popup.includes("appointments-panel"), "popup should have an appointment panel");
assert(apiJs.includes("https://www.doctolib.fr/account/appointments.json?page=0"), "popup should refresh appointments directly");
assert(optionsJs.includes("visibleApiAppointments"), "popup should filter API appointments from Doctolib flags");
assert(options.includes("patient-filter"), "patient filter setting should exist");
assert(optionsJs.includes("patientFilteredAppointments"), "appointments should be filterable by patient");
assert(optionsJs.includes("titleCaseName"), "patient names should be displayed as title case");
assert(apiJs.includes("master_patients.json"), "patient choices should come from Doctolib account people");
assert(optionsJs.includes("profilePhotoUrl"), "appointment cards should include practitioner photos");
assert(optionsJs.includes("substitute_name"), "appointment cards should show substitute practitioner names");
assert(optionsJs.includes("substitution_wording"), "appointment cards should show replacement wording");
assert(optionsJs.includes("APPOINTMENT_CACHE_SCHEMA"), "appointment cache should be schema-versioned");
assert(optionsJs.includes("APPOINTMENT_CACHE_SCHEMA = 3"), "appointment cache should include availability ids");
assert(optionsJs.includes("hasCurrentAppointmentSchema"), "popup should ignore stale normalized appointments");
assert(optionsJs.includes("agendaId: appointment.agenda_id"), "appointments should store agenda ids for availability checks");
assert(optionsJs.includes("practiceId: appointment.practice?.id"), "appointments should store practice ids for availability checks");
assert(optionsJs.includes("visitMotiveId: appointment.visit_motive?.id"), "appointments should store visit motive ids for availability checks");
assert(optionsJs.includes("showAvailabilityHint"), "appointment cards should show availability hints on hover");
assert(apiJs.includes("https://www.doctolib.fr/search/availabilities.json"), "availability hints should use the search availability endpoint");
assert(optionsJs.includes("availabilityHoverController?.abort()"), "availability hover requests should be abortable");
assert(optionsJs.includes("availabilityCache"), "availability hints should use a bounded cache");
assert(optionsJs.includes("appointmentActionButton"), "appointment cards should include action buttons");
assert(optionsJs.includes("/move/new"), "move action should open the native Doctolib move flow directly");
assert(optionsJs.includes("showCancelConfirmation"), "cancel action should show an extension confirmation dialog");
assert(apiJs.includes("method: \"DELETE\""), "cancel action should call Doctolib cancellation endpoint");
assert(apiJs.includes("cancelled_after_booking"), "cancel action should send Doctolib cancellation reason");
assert(apiJs.includes("csrfToken"), "cancel action should fetch a CSRF token before deleting");
assert(optionsJs.includes("removeCanceledAppointment"), "cancel action should remove canceled appointments locally");
assert(optionsJs.includes("rememberPendingAppointmentAction"), "popup actions should persist the requested Doctolib action");
assert(optionsJs.includes("pendingAppointmentAction"), "popup actions should use a pending action storage key");
assert(optionsJs.includes("https://www.doctolib.fr/account/appointments/details/"), "appointment cards should open the account detail appointment route");
assert(optionsJs.includes("chrome.tabs.create"), "appointment cards should open via Chrome tabs API");
assert(optionsJs.includes("openAppointmentActionWindow"), "appointment actions should open a compact Doctolib action window");
assert(optionsJs.includes("if (action === \"move\")"), "move action should open in a standard tab");
assert(optionsJs.includes("chrome.windows.create"), "appointment actions should avoid a standard new tab when possible");
assert(optionsJs.includes("state: \"normal\""), "appointment action window should avoid fullscreen state");
assert(optionsJs.includes("encodeURIComponent"), "appointment ids should be URL-safe path segments");
assert(optionsJs.includes("renderLoading"), "appointments loading spinner should exist");
assert(optionsJs.includes("appointmentsRefreshPromise"), "popup should dedupe appointment refreshes");
assert(apiJs.includes("timedFetch"), "popup fetches should have a timeout");
assert(manifest.host_permissions.includes("https://www.doctolib.fr/*"), "popup needs Doctolib host permission");
assert(manifest.host_permissions.includes("https://api-adresse.data.gouv.fr/*"), "options should validate French addresses with API Adresse");
assert(apiJs.includes("api-adresse.data.gouv.fr/search"), "options should call API Adresse");
assert(optionsJs.includes("ADDRESS_MIN_SCORE"), "address validation should use a confidence threshold");
assert(optionsJs.includes("lastAddressValidation"), "address validation should cache the last result");
assert(content.includes("findAppointmentDetailsCard"), "appointment card fallback finder should exist");
assert(content.includes("déplacer le rdv"), "appointment card should be detected from action labels");
assert(content.includes("annuler le rdv"), "appointment card should be detected from action labels");
assert(content.includes("segur-moved-facility-card"), "moved facility card spacing class should be applied");
assert(content.includes("highlightRequestedAppointmentAction"), "detail page should highlight requested action links");
assert(content.includes("triggerAppointmentAction"), "detail page should trigger requested appointment action through UI events");
assert(content.includes("PointerEvent(\"pointerdown\""), "appointment action should dispatch pointer events");
assert(content.includes("action.click()"), "appointment action should use native element activation");
assert(content.includes("loadPendingAppointmentAction"), "detail page should read pending popup actions");
assert(content.includes("clearPendingAppointmentAction"), "detail page should clear pending popup actions after triggering");
assert(content.includes("currentAppointmentId()"), "pending actions should be matched to the current appointment");
assert(content.includes("history.replaceState"), "requested appointment action hash should be cleared after triggering");
assert(!content.includes("citymapper"), "only Google Maps should remain");
assert(!content.includes("waze"), "only Google Maps should remain");
assert(!content.includes("maps.apple.com"), "only Google Maps should remain");
assert(options.includes("safety-margin"), "safety margin setting should exist");
assert(options.includes("debug-enabled"), "debug setting should exist");
assert(options.includes("🚶 À pied"), "travel mode options should include visual icons");
assert(options.includes("🚇 Transports"), "transit option should include visual icon");

console.log("smoke ok");

function assert(condition, message) {
  if (!condition) throw new Error(message);
}
